### ISSUE TITLE
Can't Compile

### ISSUE THREAD

**Issue by cerupcat** [yume190/DocCViewer#1]
I'm interested in also building a DocCViewer and came across your code. However, when I checkout the project, it's not able to build due to some issues with importing the local SPM. Any tips?

**Comment by yume190** [comment]
try newest commit

**Comment by cerupcat** [comment]
Thanks! I tried it, however a similar issue. It's not loading the local SPM.

Trying to add it gives an error. 

<img width="1856" alt="Screenshot 2024-08-14 at 9 24 49 AM" src="https://github.com/user-attachments/assets/a9e75f57-0560-4ef1-95f0-cd845b11acc0">

**Comment by cerupcat** [comment]
After updating to Xcode it seems to be working now. Thanks!
